[package]
name = "zopp-e2e-test-k8s"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "zopp-e2e-test-k8s"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
