{{- if .Values.podDisruptionBudget.operator.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zopp.fullname" . }}-operator
  labels:
    {{- include "zopp.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  {{- if .Values.podDisruptionBudget.operator.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.operator.minAvailable }}
  {{- else if .Values.podDisruptionBudget.operator.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.operator.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zopp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
{{- end }}
