{{- if and .Values.operator.enabled .Values.rbac.create }}
{{- if and (not .Values.operator.watchNamespace) (not .Values.rbac.clusterWide) }}
{{- fail "When operator.watchNamespace is empty (watch all namespaces), rbac.clusterWide must be true" }}
{{- end }}
---
{{- if .Values.rbac.clusterWide }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zopp.fullname" . }}-operator
  labels:
    {{- include "zopp.operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zopp.fullname" . }}-operator
  labels:
    {{- include "zopp.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zopp.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "zopp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "zopp.fullname" . }}-operator
  {{- if .Values.operator.watchNamespace }}
  namespace: {{ .Values.operator.watchNamespace }}
  {{- end }}
  labels:
    {{- include "zopp.operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "zopp.fullname" . }}-operator
  {{- if .Values.operator.watchNamespace }}
  namespace: {{ .Values.operator.watchNamespace }}
  {{- end }}
  labels:
    {{- include "zopp.operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "zopp.fullname" . }}-operator
subjects:
- kind: ServiceAccount
  name: {{ include "zopp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
