{{- if .Values.podDisruptionBudget.server.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zopp.fullname" . }}-server
  labels:
    {{- include "zopp.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if not (kindIs "invalid" .Values.podDisruptionBudget.server.minAvailable) }}
  minAvailable: {{ .Values.podDisruptionBudget.server.minAvailable }}
  {{- else if not (kindIs "invalid" .Values.podDisruptionBudget.server.maxUnavailable) }}
  maxUnavailable: {{ .Values.podDisruptionBudget.server.maxUnavailable }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "zopp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
