{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zopp.fullname" . }}-server
  labels:
    {{- include "zopp.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.server.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zopp.server.selectorLabels" . | nindent 4 }}
{{- end }}
